blueprint:
  name: Motion Lights
  description: Turn on and off lights, based on a lot ofconditionss
  domain: automation

  input:
    motion_sensor:
      name: Motion Sensor
      description: Movement detection
      selector:
        entity:
          filter:
            - domain: binary_sensor
            - device_class: motion
    lights:
      name: Lights
      description: The set of lights to turn on and off
      selector:
        target:
          entity:
            - domain: light
    off_delay:
      name: Off delay
      description: Delay in which to turn off the light after the motion is off
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: "minutes"
      default: 0
    door:
      name: Door
      description: If the door is closed, the light will not turn on / off
      default: [] 
      selector:
        entity:
          filter:
            - domain: binary_sensor
    night:
      name: Night
      description: Do not turn on lights during the day
      default: off
      selector:
        boolean:
    tv:
      name: Tv
      description: A Tv than control the lights. When the media runs, the lights turns off. When the media pause, the light turns on.
      default: []
      selector:
        entity:
          filter:
            - domain: media_player
    button_on:
      name: Button On
      default: []
      description: A button to turn on the lights
      selector:
        entity:
          filter:
            - domain: input_button
    button_off:
      name: Button Off
      default: []
      description: A button to turn off the lights
      selector:
        entity:
          filter:
            - domain: input_button

mode: restart  
variables:
  night_enabled: !input night
  night: "{{ night_enabled != true or states('input_boolean.night') == 'on' }}"
  motion: !input motion_sensor
  lights: !input lights
  door_entity: !input door
  door: "{{ door_entity == [] or states(door_entity) == 'on' }}"
  brightness: >
    {% if states.input_boolean.sleep.state == 'off' or states.input_boolean.guest == 'on' %}
      100
    {% else %}
      10
    {% endif %}
  tv_entity: !input tv
  tv_off: "{{ tv_entity == [] or states(tv_entity) == 'unavailable' }}"
  tv_pause: "{{ tv_entity != [] and states(tv_entity) != 'unavailable' and states(tv_entity) != 'playing' }}"
  tv_playing: "{{ tv_entity != [] and states(tv_entity) == 'playing' }}"

trigger_variables:
  off_delay: !input off_delay

trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"
    id: "motion_on"  
  - platform: state
    entity_id: !input motion_sensor
    from: "on"
    to: "off"
    for:
      minutes: !input off_delay
    id: "motion_half"
  - platform: state
    entity_id: !input motion_sensor
    from: "on"
    to: "off"
    for:
      minutes: "{{ off_delay + 1 }}"
    id: "motion_off"

  - platform: state
    id: "night"
    entity_id: input_boolean.night
  - platform: state
    entity_id: !input tv
    id: "tv"
  - platform: state
    entity_id: !input button_on
    id: "button_on"

action:
  - choose:
    - conditions:
        - condition: template
          alias: "motion on"
          value_template: "{{ trigger.id == 'motion_on' and night == true and door == true and tv_off == true }}"
      sequence:
        - service: light.turn_on
          target: !input lights
          data:
            brightness_pct: "{{ brightness }}"
    - conditions:
        - condition: template
          alias: "night on"
          value_template: "{{ trigger.id == 'night' and trigger.to_state.state == 'on' and states(motion) == 'on' and night_enabled == true and door == true and tv_off == true }}"
      sequence:
        - service: light.turn_on
          target: !input lights
          data:
            brightness_pct: "{{ brightness }}"
    - conditions:
        - condition: template
          alias: "motion half off"
          value_template: "{{ trigger.id == 'motion_half' and door == true and night == true and tv_off == true }}" 
      sequence:
        - service: light.turn_on
          target: !input lights
          data:
            brightness_pct: "{{ brightness / 10 }}"
    - conditions:
        - condition: template
          alias: "motion off"
          value_template: "{{ trigger.id == 'motion_off' and door == true and tv_off == true }}" 
      sequence:
        - service: light.turn_off
          target: !input lights

    - conditions:
        - condition: template
          alias: "night off"
          value_template: "{{ trigger.id == 'night' and trigger.to_state.state == 'off' and night_enabled == true }}" 
      sequence:
        - service: light.turn_off
          target: !input lights

    - conditions:
        - condition: template
          alias: "tv on"
          value_template: "{{ (trigger.id == 'tv' or trigger.id == 'night') and tv_pause == true and night == true }}"
      sequence:
        - service: light.turn_on
          target: !input lights
          data:
            brightness_pct: "{{ brightness / 10 }}"
    - conditions:
        - condition: template
          alias: "tv playing"
          value_template: "{{ trigger.id == 'tv' and tv_playing == true }}"
      sequence:
        - service: light.turn_off
          target: !input lights
    - conditions:
        - condition: template
          alias: "tv off"
          value_template: "{{ trigger.id == 'tv' and tv_off == true and night == true }}"
      sequence:
        - service: light.turn_on
          target: !input lights
          data:
            brightness_pct: "{{ brightness }}"
    - conditions:
        - condition: template
          alias: "button on"
          value_template: "{{ trigger.id == 'button_on' }}"
      sequence:
        - service: light.turn_on
          target: !input lights
          data:
            brightness_pct: "{{ brightness }}"
    - conditions:
        - condition: template
          alias: "button off"
          value_template: "{{ trigger.id == 'button_off' }}"
      sequence:
        - service: light.turn_off
          target: !input lights
