blueprint:
  name: Motion Lights
  description: Turn on and off lights, based on a lot ofconditionss
  domain: automation

  input:
    motion_sensor:
      name: Motion Sensor
      description: Movement detection
      selector:
        entity:
          filter:
            - domain: binary_sensor
    lights:
      name: Lights
      description: The set of lights to turn on and off
      selector:
        entity:
          filter:
            - domain: light
          multiple: true
    off_delay:
      name: Off delay
      description: Delay in which to turn off the light after the motion is off
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: "minutes"
      default: 0
    door:
      name: Door
      description: If the door is closed, the light will not turn on / off
      default: [] 
      selector:
        entity:
          filter:
            - domain: binary_sensor
    window:
      name: Window
      description: If the window is open, dim the lights
      default: []
      selector:
        entity:
          filter:
            - domain: binary_sensor
    no_motion_sleep:
      name: No motion when sleeping
      description: Deactivate the motion sensor when sleeping, to not turn on the lights by accident
      default: false
      selector:
        boolean:
    lux:
      name: Lux
      description: Set a light level where the light turns on and off (0 for always on)
      default: 0
      selector:
        number:
          min: 0
          max: 1000
    tv:
      name: Tv
      description: A Tv than control the lights. When the media runs, the lights turns off. When the media pause, the light turns on.
      default: []
      selector:
        entity:
          filter:
            - domain: media_player
    button_on:
      name: Button On
      default: []
      description: A button to turn on the lights
      selector:
        entity:
          filter:
            - domain: input_button
    button_off:
      name: Button Off
      default: []
      description: A button to turn off the lights
      selector:
        entity:
          filter:
            - domain: input_button

mode: queued
variables:
  lux_value: !input lux
  lux: "{{ states('sensor.luminance_illuminance')|int }}"
  night: "{{ lux_value == 0 or states('sensor.luminance_illuminance')|int < lux_value }}"
  motion_entity: !input motion_sensor
  motion_time: "{{ as_timestamp(now()) - as_timestamp(states[motion_entity].last_changed) }}"
  motion: "{{ states(motion_entity) == 'on' or motion_time <= off_delay*60 + 10  }}"
  motion_half: "{{ states(motion_entity) == 'off' and motion_time >= off_delay*60 and motion_time <= off_delay*60 + 10 }}"
  raw_lights: !input lights
  lights: >
    {{ raw_lights if raw_lights is sequence else [raw_lights] }}
  lights_with_brightness: >
    {% set namespace = namespace(list=[]) %}
    {% for entity in lights %}
      {% set supported = state_attr(entity, 'supported_features') %}
      {% if supported is not none and (supported | int) >= 1 %}
        {% set namespace.list = namespace.list + [entity] %}
      {% endif %}
    {% endfor %}
    {{ namespace.list if namespace.list|length > 0 else lights }}
  lights_without_brightness: >
    {% set namespace = namespace(list=[]) %}
    {% for entity in lights %}
      {% set supported = state_attr(entity, 'supported_features') %}
      {% if not (supported is not none and (supported | int) >= 1) %}
        {% set namespace.list = namespace.list + [entity] %}
      {% endif %}
    {% endfor %}
    {{ namespace.list if namespace.list|length < lights|length else [] }}
  light_state: "{{ states(lights[0]) == 'on' }}"
  door_entity: !input door
  door_open: "{{ door_entity == [] or states(door_entity) == 'on' and (as_timestamp(now()) - as_timestamp(states[door_entity].last_changed)) > 60 }}"
  window_entity: !input window
  window_open: "{{ window_entity != [] and states(window_entity) == 'on' }}"
  tv_entity: !input tv
  tv_off: "{{ tv_entity == [] or states(tv_entity) == 'unavailable' }}"
  lights_off: "{{ states('input_boolean.lights_off') == 'on' }}"

  sleep: "{{ states.input_boolean.sleep.state == 'on' }}"
  guest: "{{ states.input_boolean.guest.state == 'on' }}"
  no_motion_sleep: !input no_motion_sleep

  always_turn_on: "{{ trigger.id in ['motion_on', 'night_on', 'tv_off', 'sleep'] and motion and night and door_open and tv_off and (not no_motion_sleep or not sleep) or trigger.id == 'button_on' }}"
  update_brightness: "{{ trigger.id == 'motion_half' and light_state and door_open or trigger.id in ['window', 'lights_off', 'button_on', 'tv_off'] and light_state or trigger.id == 'sleep' and (sleep and not no_motion_sleep or not sleep) and light_state }}"
  should_turn_on: "{{ always_turn_on or update_brightness }}"
  brightness: >
    {% if trigger.id == 'button_on' and light_state %}
      100
    {% elif window_open or lights_off and lux < 30 or not tv_off or sleep and not guest %}
      1
    {% elif motion_half %}
      10
    {% else %}
      100
    {% endif %}
  transition: 0.3
  lights_to_turn_on: >
    {{ lights if brightness > 15 else lights_with_brightness }}
  lights_to_turn_off: >
    {{ [] if brightness > 15 else lights_without_brightness }}
 
trigger_variables:
  off_delay: !input off_delay
  lux_value: !input lux

trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"
    id: "motion_on"  
  - platform: state
    entity_id: !input motion_sensor
    from: "on"
    to: "off"
    for:
      minutes: !input off_delay
    id: "motion_half"
  - platform: state
    entity_id: !input motion_sensor
    from: "on"
    to: "off"
    for:
      seconds: "{{ off_delay*60 + 11}}"
    id: "motion_off"
  - platform: template
    id: "night_on"
    value_template: "{{ states('sensor.luminance_illuminance')|int < lux_value - 10 }}"
  - platform: template
    id: "night_off"
    value_template: "{{ states('sensor.luminance_illuminance')|int >= lux_value }}"
  - platform: state
    entity_id: !input tv
    id: "tv_on"
    from: "unavailable"
  - platform: state
    entity_id: !input tv
    id: "tv_off"
    to: "unavailable"
  - platform: state
    entity_id: !input button_on
    id: "button_on"
  - platform: state
    entity_id: !input button_off
    id: "button_off"
  - platform: state
    entity_id: !input window
    id: "window"
  - platform: state
    entity_id: input_boolean.sleep
    id: "sleep"
  - platform: state
    entity_id: input_boolean.lights_off
    id: "lights_off"
  - platform: state
    entity_id: !input lights
    id: "lights_too_long"
    to: "on"
    for:
      hours: 8

action:
        - choose:
          - conditions:
            - condition: template
              value_template: "{{ trigger.id == 'night_off' and not night or trigger.id == 'motion_off' and door_open or trigger.id in ['button_off', 'lights_too_long', 'tv_on'] or trigger.id == 'sleep' and no_motion_sleep and sleep }}"
            sequence:
              - service: light.turn_off
                target: 
                  entity_id: !input lights
                data:
                  transition: 0.3
          - conditions:
            - condition: template
              value_template: "{{ should_turn_on }}"
            sequence:
              - service: light.turn_on
                target: 
                  entity_id: "{{ lights_to_turn_on }}"
                data:
                  transition: "{{ transition }}"
                  brightness_pct: "{{ brightness }}"
              - service: light.turn_off
                target: 
                  entity_id: "{{ lights_to_turn_off }}"
                data:
                  transition: "{{ transition }}"


