blueprint:
  name: Motion Lights
  description: Turn on and off lights, based on a lot ofconditionss
  domain: automation

  input:
    motion_sensor:
      name: Motion Sensor
      description: Movement detection
      selector:
        entity:
          filter:
            - domain: binary_sensor
            - device_class: motion
    lights:
      name: Lights
      description: The set of lights to turn on and off
      selector:
        target:
          entity:
            - domain: light
    off_delay:
      name: Off delay
      description: Delay in which to turn off the light after the motion is off
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: "minutes"
      default: 0
    door:
      name: Door
      description: If the door is closed, the light will not turn on / off
      default: [] 
      selector:
        entity:
          filter:
            - domain: binary_sensor
    night:
      name: Night
      description: Do not turn on lights during the day
      default: off
      selector:
        boolean:
mode: restart  
variables:
  night_enabled: !input night
  motion: !input motion_sensor
  lights: !input lights
  door_entity: !input door
  door: "{{ door_entity == [] or states[door_entity].state == 'on' }}"
  brightness: >
    {% if states.input_boolean.sleep.state == 'off' or states.input_boolean.guest == 'on' %}
      100
    {% else %}
      10
    {% endif %}

trigger_variables:
  off_delay: !input off_delay

trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"
    id: "motion_on"  
  - platform: state
    entity_id: !input motion_sensor
    from: "on"
    to: "off"
    for:
      minutes: !input off_delay
    id: "motion_half"
  - platform: state
    entity_id: !input motion_sensor
    from: "on"
    to: "off"
    for:
      minutes: "{{ off_delay + 1 }}"
    id: "motion_off"

  - platform: state
    id: "night"
    entity_id: input_boolean.night


action:
  - choose:
    - conditions:
        - condition: template
          value_template: "{{ trigger.id == 'motion_on' and (night_enabled != true or states.input_boolean.night.state == 'on') and door == true }}"
      sequence:
        - service: light.turn_on
          target: !input lights
          data:
            brightness_pct: "{{ brightness }}"
    - conditions:
        - condition: template
          value_template: "{{ trigger.id == 'night' and trigger.to_state.state == 'on' and states(motion) == 'on' and night_enabled == true and door == true }}"
      sequence:
        - service: light.turn_on
          target: !input lights
          data:
            brightness_pct: "{{ brightness }}"
    - conditions:
        - condition: template
          value_template: "{{ trigger.id == 'motion_half' and door == true }}" 
      sequence:
        - service: light.turn_on
          target: !input lights
          data:
            brightness_pct: "{{ brightness / 10 }}"
    - conditions:
        - condition: template
          value_template: "{{ trigger.id == 'motion_off' and door == true }}" 
      sequence:
        - service: light.turn_off
          target: !input lights

    - conditions:
        - condition: template
          value_template: "{{ trigger.id == 'night' and trigger.to_state.state == 'off' and night_enabled == true }}" 
      sequence:
        - service: light.turn_off
          target: !input lights
